# Generated by Django 3.2.3 on 2021-06-05 11:05

import adopetGeral.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoAnuncio', models.ImageField(blank=True, help_text='Escolha uma imagem', null=True, upload_to='media/fotoAnuncio')),
                ('nome', models.CharField(help_text='Nome anuncio.', max_length=50)),
                ('tipoAnimal', models.CharField(choices=[('Gato', 'Gato'), ('Cachorro', 'Cachorro')], default='Gato', help_text='Escolha o tipo do seu pet', max_length=8)),
                ('localizacao', models.TextField(help_text='Localização do animal.')),
                ('raca', models.CharField(help_text='Raça do animal', max_length=100)),
                ('porte', models.CharField(help_text='Porte do animal', max_length=100)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Femea', 'Femea')], default='Macho', help_text='Escolha o sexo do animal', max_length=5)),
                ('dataNascimento', models.DateField(help_text='dd/mm/aaaa')),
                ('personalidade', models.TextField(help_text='Personalidade do pet.')),
                ('fotoAlbum', models.ImageField(blank=True, help_text='Escolha diversas imagens', null=True, upload_to=adopetGeral.models.upload_location)),
                ('observacoes', models.TextField(help_text='Observações do pet.')),
                ('historia', models.TextField(help_text='Digite a historia do pet', null=True)),
            ],
            options={
                'verbose_name_plural': 'Anuncios',
                'db_table': 'tab_anuncioAnimal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=250, verbose_name='Nome')),
                ('dataNascimento', models.DateField(help_text='dd/mm/aaaa', verbose_name='Data de nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N/A', 'Prefiro não dizer')], default='M', help_text='Escolha o gênero', max_length=3, verbose_name='Gênero')),
                ('avatar', models.ImageField(blank=True, help_text='Escolha uma imagem', null=True, upload_to='media/avatar', verbose_name='Avatar')),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
                'db_table': 'tab_Pessoa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTipo', models.CharField(help_text='Tipo', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipo de animais',
                'db_table': 'tab_tipoAnimal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FotosAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, help_text='Escolha as fotos', upload_to=adopetGeral.models.upload_location, verbose_name='Fotos')),
                ('descricaoFoto', models.TextField(help_text='Descrição das fotos')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopetGeral.anuncioanimal')),
            ],
            options={
                'verbose_name_plural': 'Fotos dos anuncios',
                'db_table': 'tab_fotosAnuncio',
                'managed': True,
            },
        ),
    ]
