# Generated by Django 3.2.3 on 2021-06-20 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoAnuncio', models.ImageField(blank=True, help_text='Escolha uma imagem', null=True, upload_to='media/fotoAnuncio')),
                ('nome', models.CharField(help_text='Nome anuncio.', max_length=50)),
                ('tipoAnimal', models.CharField(choices=[('Gato', 'Gato'), ('Cachorro', 'Cachorro')], default='Gato', help_text='Escolha o tipo do seu pet', max_length=8)),
                ('localizacao', models.TextField(help_text='Localização do animal.')),
                ('raca', models.CharField(help_text='Raça do animal', max_length=100)),
                ('porte', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], default='Pequeno', help_text='Escolha o sexo do animal', max_length=7)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Femea')], default='Macho', help_text='Escolha o sexo do animal', max_length=5)),
                ('dataNascimento', models.DateField(help_text='dd/mm/aaaa')),
                ('personalidade', models.TextField(help_text='Personalidade do pet.')),
                ('observacoes', models.TextField(help_text='Observações do pet.')),
                ('historia', models.TextField(help_text='Digite a historia do pet', null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Anuncios',
                'db_table': 'tab_anuncioAnimal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Digite o titulo da postagem', max_length=250, verbose_name='Titulo')),
                ('capaPostagem', models.ImageField(blank=True, null=True, upload_to='media/fotoPostagem')),
                ('postagem', models.TextField(help_text='Digite sua postagem aqui')),
                ('dataCriacao', models.DateField(help_text='dd/mm/aaaa', null=True, verbose_name='Data criação')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'db_table': 'tab_Blog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=250, verbose_name='Nome')),
                ('dataNascimento', models.DateField(help_text='dd/mm/aaaa', verbose_name='Data de nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N/A', 'Prefiro não dizer')], default='M', help_text='Escolha o gênero', max_length=3, verbose_name='Gênero')),
                ('avatar', models.ImageField(blank=True, help_text='Escolha uma imagem', null=True, upload_to='media/avatar', verbose_name='Avatar')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
                'db_table': 'tab_Pessoa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FotosAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, help_text='Escolha a foto', upload_to='media/fotosAnuncio', verbose_name='Foto')),
                ('descricaoFoto', models.TextField(help_text='Descrição da foto')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopetGeral.anuncioanimal')),
            ],
            options={
                'verbose_name_plural': 'Fotos dos anuncios',
                'db_table': 'tab_fotosAnuncio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComentarioBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(help_text='Digite seu comentario')),
                ('autorComentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopetGeral.blog')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
                'db_table': 'tab_ComentarioBlog',
                'managed': True,
            },
        ),
    ]
