# Generated by Django 3.2.3 on 2021-06-17 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopetGeral', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoAnimal',
        ),
        migrations.AddField(
            model_name='anuncioanimal',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fotosanuncio',
            name='descricaoFoto',
            field=models.TextField(help_text='Descrição da foto'),
        ),
        migrations.AlterField(
            model_name='fotosanuncio',
            name='foto',
            field=models.ImageField(blank=True, help_text='Escolha a foto', upload_to='media/fotosAnuncio', verbose_name='Foto'),
        ),
    ]
