# Generated by Django 3.2.3 on 2021-06-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopetGeral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncioanimal',
            name='nomedopet',
            field=models.CharField(help_text='Nome do seu pet.', max_length=50, null=True),
        ),
    ]
