# Generated by Django 3.2.3 on 2021-06-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopetGeral', '0003_alter_anuncioanimal_nomedopet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncioanimal',
            name='nomedopet',
            field=models.TextField(blank=True, help_text='Nome do seu pet.', null=True),
        ),
    ]
