# Generated by Django 3.2.3 on 2021-06-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopetGeral', '0003_pessoa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncioanimal',
            name='porte',
            field=models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], default='Pequeno', help_text='Escolha o sexo do animal', max_length=7),
        ),
    ]
