# Generated by Django 3.2.3 on 2021-06-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopetGeral', '0004_alter_anuncioanimal_porte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncioanimal',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Femea')], default='Macho', help_text='Escolha o sexo do animal', max_length=5),
        ),
    ]
