# Generated by Django 3.2.3 on 2021-06-18 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopetGeral', '0005_alter_anuncioanimal_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Digite o titulo da postagem', max_length=250, verbose_name='Titulo')),
                ('capaPostagem', models.ImageField(blank=True, null=True, upload_to='media/fotoPostagem')),
                ('postagem', models.TextField(help_text='Digite sua postagem aqui')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
