# Generated by Django 3.2.3 on 2021-06-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopetGeral', '0006_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'managed': True, 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelTable(
            name='blog',
            table='tab_Blog',
        ),
    ]
