# Generated by Django 3.2.3 on 2021-06-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopetGeral', '0007_auto_20210618_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='atualizado',
        ),
        migrations.AlterField(
            model_name='blog',
            name='criacao',
            field=models.DateField(help_text='dd/mm/aaaa', verbose_name='Data de criacao'),
        ),
    ]
