# Generated by Django 3.2.3 on 2021-06-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopetGeral', '0008_auto_20210618_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='criacao',
        ),
    ]
