# Generated by Django 3.2.3 on 2021-06-18 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopetGeral', '0010_blog_datacriacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(help_text='Digite seu comentario')),
                ('autorComentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopetGeral.blog')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
                'db_table': 'tab_ComentarioBlog',
                'managed': True,
            },
        ),
    ]
