# Generated by Django 3.2.3 on 2021-06-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopetGeral', '0011_comentarioblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncioanimal',
            name='fotoAlbum',
        ),
    ]
